### ISSUE TITLE
CubeUpload seems to be broken. 

### ISSUE THREAD

**Issue by brucethemoose** [ShareX/CustomUploaders#129]
For both the user an anonymous script, the only URL I get back is "http://i.cubeupload.com/"

**Comment by Jaex** [comment]
Changing request URL to https:// fixed it but image links not opens for me even from their web site upload.

**Comment by brucethemoose** [comment]
Oh, how did I not see that...

Works fine for me: https://i.cubeupload.com/zFou0j.png

That was fast, thanks!

**Comment by Jaex** [comment]
That link not opens for me. I wonder is my country blocked it or website blocking my country.

**Comment by brucethemoose** [comment]
They mention something about a DNS change on their website. Might not be updated for you yet, but after a few days for it to clear out I'd be happy to test it with my VPN if you want.

Anyway, the issue isn't on the app's or script's end, as it works for me.
