### ISSUE TITLE
teknik.io now requires accounts for all services

### ISSUE THREAD

**Issue by Dyras** [ShareX/CustomUploaders#153]
Greetings! teknik.io now requires registration to be used. That means the CustomUploaders no longer work. The files upload and at 100%, it resets back to 0% and then it tries again.

https://blog.teknik.io/uncled1023/p/1693

**Comment by Jaex** [comment]
Finally I managed to find teknik account yet still I couldn't find API info anywhere about how to use authentication.

**Comment by Jaex** [comment]
Because I needed to add `$base64:text$` syntax support, you need to use latest [ShareX dev build](https://getsharex.com/docs/dev-builds) if you want to use teknik custom uploader now.
