### ISSUE TITLE
funkyimg sxcu please

### ISSUE THREAD

**Issue by Zhangsun321** [ShareX/CustomUploaders#179]
https://i.imgur.com/2VwQd9j.png

is what my screen looks like... any help would be appreciated!

**Comment by m-alice** [comment]
I tried convert [https://github.com/zenden2k/image-uploader/blob/master/Data/Scripts/funkyimg.nut](this) but failed

**Comment by Jaex** [comment]
It requires multiple requests therefore not gonna work with custom uploader system.
