### ISSUE TITLE
Jirafeau Support Added. sxcu code inside

### ISSUE THREAD

**Issue by zhdenny** [ShareX/CustomUploaders#190]
Sorry, I don't know how to do the whole commit changes pull request git junk to push this into your repository.....but below is the config for Jirafeau. It is a nice self-hosted file/image uploader

https://gitlab.com/mojo42/Jirafeau

https://pastebin.com/Q4P36kaP

**Comment by Jaex** [comment]
Pastebin is blocked in my country so can't see it.

**Comment by Efreak** [comment]
If it helps:

https://gist.githubusercontent.com/Efreak/a15e6c65f0ef8759b67af5d5a452a44a/raw/7348b8a8a046e314afce6e20f55d6c3c0014a5d1/2020-07-28_14-57-09.txt
