### ISSUE TITLE
Recorder-devices-setup.exe Detected as a Virus 

### ISSUE THREAD

**Issue by Bj007pro** [ShareX/CustomUploaders#204]
Today Comodo Antivirus detected Recorder-devices-setup.exe as a positive:

![image](https://user-images.githubusercontent.com/24400879/55282967-7eea1700-53b4-11e9-9ab7-9ddd1fdcad55.png)

Might wanna get the fix on with Comodo. :P

**Comment by Jaex** [comment]
Why open this in custom uploaders repo?

**Comment by Bj007pro** [comment]
> Why open this in custom uploaders repo?

Sorry, I didn't realize that I had.
I hardly ever post issues /a thread on GitHub so I'm not quite found how it's system works when coming to post an idea/problem/topic.

Do you want me to recreate this issue under the correct category?
