### ISSUE TITLE
OwnCloud: Upload file + Create password-protected shareable URL

### ISSUE THREAD

**Issue by strolli** [ShareX/CustomUploaders#25]
Hi there! I know ShareX supports OwnCloud out of the box... But my default OwnCloud installation only allows password-protected shareable URLs. This is not supported yet by ShareX directly. So I thought to make a CustomUploader. But this exceeds my skills.

It needs to be done in 2 steps.
1. Upload the file via WebDAV
2. Create a Share via [OwnClousd's Share API](https://doc.owncloud.org/server/7.0/developer_manual/core/ocs-share-api.html)

Somebody certainly has done this before. Please add it to the list. Thank you.
/Strolli

**Comment by Jaex** [comment]
It can't be made with custom uploader.

**Comment by strolli** [comment]
That was quick. Thank you anyway. Should a post this in the main repo of ShareX?
(I had already a look in the sources: The code is already there, but commented out.)

**Comment by Jaex** [comment]
Because I don't have host etc. already implementing OwnCloud was difficult therefore not planning to work blindly more.
