### ISSUE TITLE
Help...

### ISSUE THREAD

**Issue by kaan1karaman** [ShareX/CustomUploaders#257]
Actually this is not an issue but i can't see a help request button issue. I need help on setting up my custom URL shortener. I've successfully made the image uploader but there is no guide about custom URL shortener.

**Comment by carshn** [comment]
https://yourls.org/ works but I can't figure out how to make it work with sharex, upload script but it just tells you where to put your signature not how to get it.

**Comment by carshn** [comment]
Just figured it out (kinda got this yesterday) it's under the tools tab when you install it onto your webserver.
