### ISSUE TITLE
New support

### ISSUE THREAD

**Issue by koalang** [ShareX/CustomUploaders#258]
https://www.lsky.pro/

{
  "Version": "13.0.1",
  "DestinationType": "ImageUploader",
  "RequestMethod": "POST",
  "RequestURL": "http://img.xxika.com/api/upload",
  "Body": "MultipartFormData",
  "FileFormName": "image",
  "URL": "$json:data.url$"
}

**Comment by carshn** [comment]
If you could provide more information on what is happening that would be great.
