### ISSUE TITLE
响应内容为如下我该如何获取url

### ISSUE THREAD

**Issue by 1265578519** [ShareX/CustomUploaders#285]
URL: {"success":true,"code":"success","message":"Upload success.","data":{"file_id":0,"width":256,"height":256,"filename":"Test.png","storename":"WSfJZuTP2bi94Ik.png","size":27378,"path":"\/2020\/03\/08\/WSfJZuTP2bi94Ik.png","hash":"d4bT9laPq36sjCnH8G7prcWQmD","url":"https:\/\/i.loli.net\/2020\/03\/08\/WSfJZuTP2bi94Ik.png","delete":"https:\/\/sm.ms\/delete\/d4bT9laPq36sjCnH8G7prcWQmD","page":"https:\/\/sm.ms\/image\/WSfJZuTP2bi94Ik"},"RequestId":"6C2C7F20-FB9D-4AE6-86C1-6437DCFD9797"}

OR

URL: {"success":false,"code":"image_repeated","message":"Image upload repeated limit, this image exists at: https:\/\/i.loli.net\/2020\/03\/08\/WSfJZuTP2bi94Ik.png","images":"https:\/\/i.loli.net\/2020\/03\/08\/WSfJZuTP2bi94Ik.png","RequestId":"9F919157-AF31-4BE0-B74F-0106661DF8EB"}

**Comment by 1265578519** [comment]
我使用$json:data.url$无法获取到第二个例子的url

**Comment by 1265578519** [comment]
同时写$json:data.url$$json:images$可以了。。

**Comment by ShahadatRD** [comment]
Get me the request you're sending @1265578519

**Comment by 1265578519** [comment]
@ShahadatRD 这个问题解决了。可以写多个$$同时匹配

**Comment by enescglyn** [comment]
> @ShahadatRD problem has been solved. You can write multiple $$s to match at the same time.

If the problem has been solved, please close the issue.
