### ISSUE TITLE
boring.host returns with (403) Forbidden.

### ISSUE THREAD

**Issue by ShahadatRD** [ShareX/CustomUploaders#288]
Here's the response

> Error message:
The remote server returned an error: (403) Forbidden.

Request URL:
https://api.boring.host/api/v1/upload

Status code:
(403) Forbidden

Headers:
Connection: keep-alive
pragma: no-cache
CF-Cache-Status: DYNAMIC
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Content-Type-Options: nosniff
CF-RAY: 58a25412b93eed03-SJC
cf-request-id: 025952dfb60000ed03a3a95200000001
Content-Length: 38
Cache-Control: private, must-revalidate
Content-Type: application/json
Date: Sun, 26 Apr 2020 18:22:18 GMT
Expires: -1
Set-Cookie: __cfduid=d3c9fe3bf473decdc9470931e859d5e8a1587925338; expires=Tue, 26-May-20 18:22:18 GMT; path=/; domain=.boring.host; HttpOnly; SameSite=Lax; Secure
Server: cloudflare

Response text:
{"success":false,"message":"Disabled"}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by iraizo** [comment]
<a href="https://github.com/ShareX/CustomUploaders/pull/313">Pull request</a>, seems like the API is down since days
