### ISSUE TITLE
Add Wordpress Custom Uploader

### ISSUE THREAD

**Issue by abclution** [ShareX/CustomUploaders#302]
Its a bit over my capabilities, but uploading directly to Wordpress media library would be freaking cool. This would be self-hosted wordpress, not their blog platform..

 As I said its a bit over my head but thought I would put the idea out there.

The following is some example code using a REST and post method. 
https://gist.github.com/websupporter/18610e717704b572a8c40c3e2b4af93a

**Comment by neumaticc** [comment]
This may be possible just using FTP or if you want, php (e,g [JoeGandy/ShareX-Custom-Upload](https://github.com/JoeGandy/ShareX-Custom-Upload))
