### ISSUE TITLE
add imageban.ru

### ISSUE THREAD

**Issue by g0blin-NN** [ShareX/CustomUploaders#351]
https://imageban.ru/
Sorry, only in Russian
https://imageban.ru/api

**Comment by D0LLYNH0** [comment]
I just opened a pull request for this site, just go to request [#361](https://github.com/ShareX/CustomUploaders/pull/361).

Don't forget to replace `YOUR_CLIENT_ID` and `YOUR_SECRET_KEY` with your credentials.

**Comment by g0blin-NN** [comment]
thanks. working.
