### ISSUE TITLE
custom file name

### ISSUE THREAD

**Issue by Yuelioi** [ShareX/CustomUploaders#359]
I want to input a custome filename, just like  202107082030-A.jpg. I can do it well with "%y%mo%d%h%mi-%ra.jpg"
but when i want to import a gif, it can't fit. 

Is there some variable can fit ext？like %y%mo%d%h%mi-%ra.$ext$
I only find  $filenamenoext$

**Comment by erbanku** [comment]
Hello Yuelioi:
I think you can change the file naming from `%y%mo%d%h%mi-%ra.jpg` to `%y%mo%d%h%mi-%ra`
In this circumstance ShareX will auto handle all extensions files name with that format.

**Comment by Yuelioi** [comment]
> 您好Yuelioi：
> 我认为您可以将文件命名从 更改`%y%mo%d%h%mi-%ra.jpg`为`%y%mo%d%h%mi-%ra`
> 在这种情况下，ShareX 将自动处理该格式的所有扩展名文件名。

Thanks! Before your reply, I use settings - upload settings - file rename : %y%mo%d%h%mi%s , 
and change my custom key to "$input$"
