### ISSUE TITLE
Allow image uploader and file uploader to PUT

### ISSUE THREAD

**Issue by tjrobinson** [ShareX/CustomUploaders#49]
I'm trying to write a custom uploader that uses the Azure Blob Storage REST API but this only supports blobs (files) being added using PUT, whereas ShareX only allows POST to be used.

**Comment by zeffy** [comment]
I'm pretty sure ShareX supports PUT from the custom uploaders dialog, under request type.

**Comment by tjrobinson** [comment]
@zeffy This is what I'm seeing (the message in the bottom right):

![image](https://cloud.githubusercontent.com/assets/925311/18635011/4f91ae20-7e7b-11e6-91d0-7e236bd54687.png)

- https://github.com/ShareX/ShareX/blob/f59f568b9b9051147de194a09004ce703573ef08/ShareX.UploadersLib/ImageUploaders/CustomImageUploader.cs#L82
- https://github.com/ShareX/ShareX/blob/f59f568b9b9051147de194a09004ce703573ef08/ShareX.UploadersLib/ImageUploaders/CustomImageUploader.cs#L82

**Comment by zeffy** [comment]
Huh, my bad, you're right. After reviewing the source, it looks like PUT and other non-POST methods are only allowed for URL shorteners and text uploaders. I wonder what the reason for that is?

**Comment by tjrobinson** [comment]
@zeffy Yea, it's not obvious to me why the check is there. Perhaps @Jaex knows as he made the change in this commit: https://github.com/ShareX/ShareX/commit/21a6d850b15bfecd7f78071dd4b20ac79dd7aeca

**Comment by Jaex** [comment]
This issues section for custom uploader script related issues (like this: #2). Not for ShareX related issues.
