### ISSUE TITLE
up1 support

### ISSUE THREAD

**Issue by huggenknubbel** [ShareX/CustomUploaders#50]
where is the Up1 support since the last update?

**Comment by KSib** [comment]
The reason is in the [changelog](https://github.com/ShareX/ShareX/wiki/Changelog)

> Removed up1.ca file uploader because service is down now

**Comment by huggenknubbel** [comment]
but everyone can host the service self.
like me.

2016-10-06 20:30 GMT+02:00 KSib <notifications@github.com>:

**Comment by KSib** [comment]
Could you re-write that? I don't quite follow. 

Thanks.

**Comment by magentic** [comment]
Up1 is open-source and can be self-hosted. https://github.com/Upload/Up1
I was using it fine with my own private server.
After upgrading to ShareX 11.3, it just stopped working.
