### ISSUE TITLE
Cubeupload User Info

### ISSUE THREAD

**Issue by xCryptic** [ShareX/CustomUploaders#51]
https://github.com/ShareX/CustomUploaders/blob/master/cubeupload.com%20(User).json

I'm a little confused as to where I'm supposed to get the user hash and user id. I can't find anywhere on cubeupload that gives that info.

**Comment by Jaex** [comment]
I could only find them in page source codes.

**Comment by xCryptic** [comment]
Where at in the page source?

**Comment by Jaex** [comment]
Search user_hash in main page source.

**Comment by xCryptic** [comment]
Ah, I see. Thanks for your help.
