### ISSUE TITLE
filebox.moe support

### ISSUE THREAD

**Issue by Fytcher** [ShareX/CustomUploaders#58]
Hey could you add filebox.moe to the pomf uploaders? 
[filebox.moe.txt](https://github.com/ShareX/CustomUploaders/files/637944/filebox.moe.txt)

**Comment by Fytcher** [comment]
It is reachable. Please check again

**Comment by Jaex** [comment]
Okey adding it to pomf uploaders list then.

**Comment by Fytcher** [comment]
Thanks :)
