### ISSUE TITLE
postimage.io/old.postimage.org Support

### ISSUE THREAD

**Issue by zerotag** [ShareX/CustomUploaders#71]
Not really an Issue, just a request (I tried but failed hard).
Also, can you configure, so the URL response to be the direct image link? (Not sure if possible)

For
https://postimage.io/
Or
https://old.postimage.org/

Thank you.

--Edit
To be fair, would love a section inside destinations for this website as well, because I have an account and I like history catalogs of such. (Just an idea thou)

**Comment by Jaex** [comment]
They made that web site in 2004 and still active. And yet there is no public API. Which means they don't want other applications to use their service.

**Comment by zerotag** [comment]
Oh, I see, they do indeed have an application, that uses, like "SomeImage",  an API Key, but I guess it's still not public. Thank you for the attention nonetheless!
