### ISSUE TITLE
CloudApp

### ISSUE THREAD

**Issue by aequasi** [ShareX/CustomUploaders#72]
Not sure how possible this would be. Looks like their upload requires two post requests?

https://www.getcloudapp.com/

**Comment by Jaex** [comment]
Custom uploader not supports two requests.

**Comment by aequasi** [comment]
Is that not something you'd look in to supporting?

**Comment by Jaex** [comment]
Making custom uploader be able to support multiple requests will make UI very complicated.

**Comment by aequasi** [comment]
Could do it with tabs for each request/response
