### ISSUE TITLE
Uploadpie updated, needs auth code now

### ISSUE THREAD

**Issue by Metaa** [ShareX/CustomUploaders#77]
Hey.
So now you need an auth code for UploadPie.
It's not hard to get one, just sign up.

But I'm not too sure how you'd upload a file for UploadPie anymore.
I saw there is a cookie named ``pie_auth=AUTHCODEHERE``, but setting it as a header doesn't work at all.
The form itself didn't change but you first need to supply the code somehow.

Sending the code along with the other form fields yields an "invalid auth code" error.

Does someone know what to do?

**Comment by Jaex** [comment]
Custom uploader not supports cookies.
