### ISSUE TITLE
I would appreciate assistance :D

### ISSUE THREAD

**Issue by Pixel0100** [ShareX/CustomUploaders#79]
When attempting to use my custom uploader I get the following error from the test

```
Error: Message:
The remote server returned an error: (403) Forbidden.

Request URL:
http://pixel.tf/upload.php

Response:
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous users does not have storage.objects.create access to bucket pixel.tf.</Details></Error>

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

```
I don't know how to become not an 'Anonymous user' and would like assistance 
(I'm not even sure if this is the right place to ask this kind of thing :/ )
Thanks

**Comment by iplogger** [comment]
It looks like your hosting doesn't allow you to execute php, the raw files are sent to the client.

**Comment by Pixel0100** [comment]
How do I allow Google Cloud hosting to execute the php?

**Comment by iplogger** [comment]
Not sure if this is what you want but a quick search lead me to https://cloud.google.com/php/

**Comment by Jaex** [comment]
These are server related issues and not to do with custom uploader.
